import os

replacements = {
    "errorMessage.value = '获取国家列表失败，请稍后重试?;": "errorMessage.value = '获取国家列表失败，请稍后重试。';",
    "errorMessage.value = '无法加载分类选项?;": "errorMessage.value = '无法加载分类选项。';",
    "errorMessage.value = '无法加载商品详情?;": "errorMessage.value = '无法加载商品详情。';",
    "errorMessage.value = '操作失败，请检查网络?;": "errorMessage.value = '操作失败，请检查网络。';",
    "profileSuccess.value = '资料更新成功?;": "profileSuccess.value = '资料更新成功。';",
    "profileError.value = error.response?.data?.error || '更新失败，请重试?;": "profileError.value = error.response?.data?.error || '更新失败，请重试。';",
    "passwordError.value = '两次输入的新密码不一?;": "passwordError.value = '两次输入的新密码不一致';",
    "passwordSuccess.value = '密码修改成功?;": "passwordSuccess.value = '密码修改成功。';",
    "passwordError.value = error.response?.data?.error || '修改失败，请重试?;": "passwordError.value = error.response?.data?.error || '修改失败，请重试。';",
    "errorMessage.value = '无法加载菜单权限列表?;": "errorMessage.value = '无法加载菜单权限列表。';",
    "errorMessage.value = '无法加载角色详情?;": "errorMessage.value = '无法加载角色详情。';",
    "errorMessage.value = '操作失败，请检查网络或联系管理员?;": "errorMessage.value = '操作失败，请检查网络或联系管理员。';",
    "errorMessage.value = \"无法加载国家选项，请重试?;": "errorMessage.value = \"无法加载国家选项，请重试。';",
    "errorMessage.value = \"无法加载表单选项，请重试?;": "errorMessage.value = \"无法加载表单选项，请重试。';",
    "errorMessage.value = '无法加载店铺详情?;": "errorMessage.value = '无法加载店铺详情。';",
    "errorMessage.value = '操作失败，请检查网络或联系管理员?;": "errorMessage.value = '操作失败，请检查网络或联系管理员。';",
    "errorMessage.value = '无法加载产品或店铺列表，请重试?;": "errorMessage.value = '无法加载产品或店铺列表，请重试。';",
    "errorMessage.value = '加载此商品详情失败，请关闭后重试?;": "errorMessage.value = '加载此商品详情失败，请关闭后重试。';",
    "errorMessage.value = error.response?.data?.error || '操作失败，请稍后重试?;": "errorMessage.value = error.response?.data?.error || '操作失败，请稍后重试。';",
    "errorMessage.value = '您没有权限查看此内容?;": "errorMessage.value = '您没有权限查看此内容。';",
    "errorMessage.value = '获取用户列表失败，请稍后重试?;": "errorMessage.value = '获取用户列表失败，请稍后重试。';",
    "errorMessage.value = '无法加载角色列表，新?": "errorMessage.value = '无法加载角色列表，新增';",
    "编辑功能将不可用?;": "编辑功能将不可用。';",
    "alert('无法删除内置超级管理员账?);": "alert('无法删除内置超级管理员账号');",
    "alert(\"请选择有效的店?);": "alert(\"请选择有效的店铺\");",
    "alert(\"请至少选择一条数?);": "alert(\"请至少选择一条数据\");",
    "if (!confirm('确定要删除这个日程吗?)) return;": "if (!confirm('确定要删除这个日程吗？')) return;",
    "errorMessage.value = '操作失败，请检查网络或联系管理员?;": "errorMessage.value = '操作失败，请检查网络或联系管理员。';",
    "errorMessage.value = '无法加载责任人下拉列表?;": "errorMessage.value = '无法加载责任人下拉列表。';",
    "errorMessage.value = '更新失败，请刷新页面?;": "errorMessage.value = '更新失败，请刷新页面。';",
    "const name = prompt('请输入新事项的名?');": "const name = prompt('请输入新事项的名称');",
    "errorMessage.value = '创建事项失败?;": "errorMessage.value = '创建事项失败。';",
    "const name = prompt('请输入新板块的名?');": "const name = prompt('请输入新板块的名称');",
    "errorMessage.value = '创建板块失败?;": "errorMessage.value = '创建板块失败。';",
    "if (!confirm('确定要删除这个事项吗?)) return;": "if (!confirm('确定要删除这个事项吗？')) return;",
    "errorMessage.value = '删除事项失败?;": "errorMessage.value = '删除事项失败。';",
    "errorMessage.value = '删除板块失败?;": "errorMessage.value = '删除板块失败。';",
    "errorMessage.value = '获取链接列表失败?;": "errorMessage.value = '获取链接列表失败。';",
    "errorMessage.value = '导出失败，请重试?;": "errorMessage.value = '导出失败，请重试。';",
    "errorMessage.value = '无法加载表单选项?;": "errorMessage.value = '无法加载表单选项。';",
    "errorMessage.value = error.response?.data?.error || '更新失败，请重试?;": "errorMessage.value = error.response?.data?.error || '更新失败，请重试。';",
    "errorMessage.value = '无法加载店铺选项，请联系管理员?;": "errorMessage.value = '无法加载店铺选项，请联系管理员。';",
    "errorMessage.value = '无法加载财务选项，请联系管理员?;": "errorMessage.value = '无法加载财务选项，请联系管理员。';",
    "errorMessage.value = '提交失败，请检查网络或联系管理?;": "errorMessage.value = '提交失败，请检查网络或联系管理员。';",
    "errorMessage.value = '获取数据失败，请重试?;": "errorMessage.value = '获取数据失败，请重试。';",
    "if (confirm('确定要删除这条支出数据吗？此操作不可逆?)) {": "if (confirm('确定要删除这条支出数据吗？此操作不可逆。')) {",
    "errorMessage.value = error.response?.data?.error || '删除失败，请重试?;": "errorMessage.value = error.response?.data?.error || '删除失败，请重试。';",
    "errorMessage.value = countriesError.value || '无法加载 SKU 和国家列?;": "errorMessage.value = countriesError.value || '无法加载 SKU 和国家列表';",
    "errorMessage.value = e.response?.data?.error || '获取详情失败，可能是服务器错误或数据不一致?;": "errorMessage.value = e.response?.data?.error || '获取详情失败，可能是服务器错误或数据不一致。';",
    "errorMessage.value = '您没有权限查看此内容?;": "errorMessage.value = '您没有权限查看此内容。';",
    "errorMessage.value = '获取周报列表失败，请稍后重试?;": "errorMessage.value = '获取周报列表失败，请稍后重试。';",
    "if (!confirm('确定要删除这份周报吗？该操作不可恢复?)) {": "if (!confirm('确定要删除这份周报吗？该操作不可恢复。')) {",
    "errorMessage.value = '提交失败，请检查网络或联系管理员?;": "errorMessage.value = '提交失败，请检查网络或联系管理员。';",
    "errorMessage.value = error.message || '无法加载店铺链接列表?;": "errorMessage.value = error.message || '无法加载店铺链接列表。';",
    "errorMessage.value = '请选择一个商品链?;": "errorMessage.value = '请选择一个商品链接';",
    "errorMessage.value = error.response?.data?.error || '更新失败，请重试?;": "errorMessage.value = error.response?.data?.error || '更新失败，请重试。';",
    "errorMessage.value = '获取数据失败，请重试?;": "errorMessage.value = '获取数据失败，请重试。';",
    "if (confirm('确定要删除这条销售数据吗？此操作不可逆?)) {": "if (confirm('确定要删除这条销售数据吗？此操作不可逆。')) {",
    "errorMessage.value = error.response?.data?.error || '删除失败，请重试?;": "errorMessage.value = error.response?.data?.error || '删除失败，请重试。';",
    "// (获取单个国家的详?": "// (获取单个国家的详情)",
    "// (注意: 后端没有 GET /countries/:id 接口，但我们可以?GET /countries 列表中筛?": "// (注意: 后端没有 GET /countries/:id 接口，但我们可以从 GET /countries 列表中筛选)",
    "// (更新：我们还是在父组件中获取详情，然后传?": "// (更新：我们还是在父组件中获取详情，然后传入)",
    "// (更新2：后端已?</stores/:id，我们应该也?</countries/:id 添加一?": "// (更新2：后端已有了 /stores/:id，我们应该也给 /countries/:id 添加一个)",
    "// (注：?`management.js` 中我们没有添?GET /:id，所以我们在此处获取列表并筛?": "// (注：在 `management.js` 中我们没有添加 GET /:id，所以我们在此处获取列表并筛选)",
    "// (A) 【编辑】模?": "// (A) 【编辑】模式",
    "// (B) 【创建】模?": "// (B) 【创建】模式",
    "import CountryFormModal from './CountryFormModal.vue'; // ⬅️ 导入新弹?": "import CountryFormModal from './CountryFormModal.vue'; // ⬅️ 导入新弹窗",
    "// (创建?": "// (创建)",
    "// (更新?": "// (更新)",
    "// (确保所有字段都被填充，null/undefined 转为空字符串或默认?": "// (确保所有字段都被填充，null/undefined 转为空字符串或默认值)",
    "// (附加布尔?": "// (附加布尔值)",
    "// On desktop, auto-select first. On mobile, maybe not?": "// On desktop, auto-select first. On mobile, maybe not?",
    "const previewUrl = ref(null); // (用于新图片预?": "const previewUrl = ref(null); // (用于新图片预览)",
    "if (!authStore.avatarUrl) return 'https://via.placeholder.com/150'; // 默认?": "if (!authStore.avatarUrl) return 'https://via.placeholder.com/150'; // 默认值",
    "// (当昵称在 store 中变化时，更新表?": "// (当昵称在 store 中变化时，更新表单)",
    "// (客户端验?": "// (客户端验证)",
    "// ⬇️ 【新增?": "// ⬇️ 【新增】",
    "const dialogTitle = computed(() => isEditMode.value ? '编辑角色与权? : '创建新角?);": "const dialogTitle = computed(() => isEditMode.value ? '编辑角色与权限' : '创建新角色');",
    "// (新增) 获取系统所有可用的菜单?": "// (新增) 获取系统所有可用的菜单项",
    "console.error('获取菜单项失?', error);": "console.error('获取菜单项失败', error);",
    "// 2. (核心) 预先勾选该角色已有的权?": "// 2. (核心) 预先勾选该角色已有的权限",
    "// (重置) 总是先清?": "// (重置) 总是先清空",
    "// 【编辑】模?": "// 【编辑】模式",
    "// (注意顺序：先获取所有菜单，再获取角色详?": "// (注意顺序：先获取所有菜单，再获取角色详情)",
    "// 【创建】模? (什么都不用做，表单已重?": "// 【创建】模式 (什么都不用做，表单已重置)",
    "// (修改) 重置表单 (现在也重置菜?": "// (修改) 重置表单 (现在也重置菜单)",
    "placeholder=\"例如: Shopee 印尼 Mall ?": "placeholder=\"例如: Shopee 印尼 Mall 店\"",
    "countryCode: '', // ⬅️ 【修改?": "countryCode: '', // ⬅️ 【修改】",
    "// countries: [], // (已删?": "// countries: [], // (已删除)",
    "const countriesList = ref([]); // ⬅️ 【新增?": "const countriesList = ref([]); // ⬅️ 【新增】",
    "// (不变) 计算属?": "// (不变) 计算属性",
    "const dialogTitle = computed(() => isEditMode.value ? '编辑店铺' : '创建新店?);": "const dialogTitle = computed(() => isEditMode.value ? '编辑店铺' : '创建新店铺');",
    "// ⬇️ 【修改?": "// ⬇️ 【修改】",
    "countryCode: store.countryCode, // ⬅️ 【修改?": "countryCode: store.countryCode, // ⬅️ 【修改】",
    "// ⬅️ (关键) `formData` 中现在是 `countryCode`?": "// ⬅️ (关键) `formData` 中现在是 `countryCode`。",
    "//    这与我们后端 `storeSchema` 期望的一?": "//    这与我们后端 `storeSchema` 期望的一致",
    "//    (或? ? PUT /stores/:id 返回一个包? country 的对?": "//    (或者， PUT /stores/:id 返回一个包含 country 的对象)",
    "//    (为了简单起见，我们先按原样发送，在下一个文? `StoreManagement.vue` 中处?": "//    (为了简单起见，我们先按原样发送，在下一个文件 `StoreManagement.vue` 中处理)",
    "// (为了正确更新UI, 我们需要返回包含country对象的数?": "// (为了正确更新UI, 我们需要返回包含country对象的数据)",
    "emit('store-updated'); // (修改) 不再发送数据，只发送信?": "emit('store-updated'); // (修改) 不再发送数据，只发送信号",
    "placeholder=\"例如：Vega Pro 官方旗舰?": "placeholder=\"例如：Vega Pro 官方旗舰店\"",
    "placeholder=\"请输入在售价?": "placeholder=\"请输入在售价格\"",
    "角色与权?": "角色与权限",
    "已?{{ selectedCount }} ?(?{{ previewData.length }} ?)?": "已选 {{ selectedCount }} 项 (共 {{ previewData.length }} 项)",
    "其中未匹?<span class=\"text-red-600 font-bold\">{{ selectedUnmatchedCount }}</span> ?": "其中未匹配 <span class=\"text-red-600 font-bold\">{{ selectedUnmatchedCount }}</span> 项",
    "上一?": "上一页",
    "?{{ currentPage }} / {{ totalPages }} ?": "第 {{ currentPage }} / {{ totalPages }} 页",
    "下一?": "下一页",
    "placeholder=\"例如: 财务后台 (可?\"": "placeholder=\"例如: 财务后台 (可选)\"",
    "// 【编辑】模? 预填充表?": "// 【编辑】模式 预填充表单",
    "placeholder=\"例如: 检? Shopee 印尼站广告花?": "placeholder=\"例如: 检查 Shopee 印尼站广告花费\"",
    "“{{ countryCode }}”国家暂无数据?": "“{{ countryCode }}”国家暂无数据。",
    "点此创建第一个板?": "点此创建第一个板块",
    "import EditableCell from './EditableCell.vue'; // ⬅️ 导入新组?": "import EditableCell from './EditableCell.vue'; // ⬅️ 导入新组件",
    "// (监视) 当国家代码变化时，重新获取数?": "// (监视) 当国家代码变化时，重新获取数据",
    "// (启动?": "// (启动时)",
    "// ⬇️ 【修复?": "// ⬇️ 【修复】",
    "// ⬆️ 【修复?": "// ⬆️ 【修复】",
    "fetchData(props.countryCode); // (硬刷?": "fetchData(props.countryCode); // (硬刷新)",
    "目前还没有常用链接?": "目前还没有常用链接。",
    "import LinkModal from './LinkModal.vue'; // 导入新弹?": "import LinkModal from './LinkModal.vue'; // 导入新弹窗",
    "// 弹窗状?": "// 弹窗状态",
    "if (confirm(`确定要删?\"${link.title}\" 吗？`)) {": "if (confirm(`确定要删除 \"${link.title}\" 吗？`)) {",
    "fetchLinks(); // 删除后重新加?": "fetchLinks(); // 删除后重新加载",
    "// (这部分已由后端在 GET /api/recurring-tasks 中处?": "// (这部分已由后端在 GET /api/recurring-tasks 中处理)",
    "return props.planNextWeek?.trim() ? props.planNextWeek : '暂无计划内容，请在周报中填写“下周计划”?": "return props.planNextWeek?.trim() ? props.planNextWeek : '暂无计划内容，请在周报中填写“下周计划”。';",
    "return props.teamFocus?.trim() ? props.teamFocus : '管理员尚未发布本周聚焦内容?": "return props.teamFocus?.trim() ? props.teamFocus : '管理员尚未发布本周聚焦内容。';",
    "请下载模板，按照模板格式填写数据后上传?(仅限管理?": "请下载模板，按照模板格式填写数据后上传。(仅限管理员)",
    "成功导入: {{ importResult.importedCount }} ?": "成功导入: {{ importResult.importedCount }} 条",
    "失败: {{ importResult.failedCount }} ?": "失败: {{ importResult.failedCount }} 条",
    "根据日期范围导出支出数据? Excel 文件?": "根据日期范围导出支出数据为 Excel 文件。",
    "failedRows: [{ row: '?', error: error.response?.data?.error || '上传失败，请检查文件格式或联系管理? }]": "failedRows: [{ row: '?', error: error.response?.data?.error || '上传失败，请检查文件格式或联系管理员。' }]",
    "'Shopee 印尼 Mall ?, '11月第一?": "'Shopee 印尼 Mall 店', '11月第一周'",
    "{ wch: 15 }, // 付款?": "{ wch: 15 }, // 付款方",
    "{ wch: 15 }, // 收款?": "{ wch: 15 }, // 收款方",
    "{ wch: 10 }, // 票据状?": "{ wch: 10 }, // 票据状态",
    "responseType: 'blob', // ⬅️ (关键) 告诉 axios 我们在下载文?": "responseType: 'blob', // ⬅️ (关键) 告诉 axios 我们在下载文件",
    "// (防止在加载时被清?": "// (防止在加载时被清空)",
    "// 2. 复制数据到表?": "// 2. 复制数据到表单",
    "????": "提交",
    "// (成功后重置表?": "// (成功后重置表单)",
    "// 筛选器状?": "// 筛选器状态",
    "// 弹窗状?": "// 弹窗状态",
    "// (生命周期) 页面加载?": "// (生命周期) 页面加载时",
    "// (权限) Admin 看所有，主管只看自己负责?": "// (权限) Admin 看所有，主管只看自己负责的",
    "// (移除? platform 筛?": "// (移除了 platform 筛选)",
    "// 4. 操作 (筛选、重置、排?": "// 4. 操作 (筛选、重置、排序)",
    "placeholder=\"可?": "placeholder=\"可选\"",
    "placeholder=\"? 同捆?": "placeholder=\"如 同捆包\"",
    "3. 物流预填 (可?": "3. 物流预填 (可选)",
    "title=\"更新状?": "title=\"更新状态\"",
    "// (只保留了 props, emits, 和辅助函?": "// (只保留了 props, emits, 和辅助函数)",
    "// 重置状?": "// 重置状态",
    "// 初始化表?": "// 初始化表单",
    "// 初始化日期输?": "// 初始化日期输入",
    "?<span class=\"font-medium\">{{ total }}</span> ?": "共 <span class=\"font-medium\">{{ total }}</span> 条",
    "修改销售数?": "修改销售数据",
    "提示：这是一条旧数据，请重新关联到一个具体的商品链接?": "提示：这是一条旧数据，请重新关联到一个具体的商品链接。",
    "'RETURNED': '已退?": "'RETURNED': '已退货'",
    "// 如果是初次加载（oldStoreId ? undefined）且 storeId 没变，则不清?": "// 如果是初次加载（oldStoreId 为 undefined）且 storeId 没变，则不清空",
    "// 保留 listingId，不做操?": "// 保留 listingId，不做操作",
    "formData.value.listingId = ''; // 切换店铺时清?": "formData.value.listingId = ''; // 切换店铺时清空",
    "// 1. 复制数据到表?": "// 1. 复制数据到表单",
    "显示?": "显示",
    "?": "共",
    "条，?": "条，共",
    "?": "页",
    "// 分页状?": "// 分页状态",
    "// 兼容旧接?": "// 兼容旧接口",
    "// 新分页接?": "// 新分页接口",
    "console.error('获取销售数据失?', error);": "console.error('获取销售数据失败', error);",
    "// ... (后续代码? countryOptions, platformOptions 等保持不?": "// ... (后续代码如 countryOptions, platformOptions 等保持不变)",
    "fetchData(true); // 重置筛选时也重置页?": "fetchData(true); // 重置筛选时也重置页码",
    "fetchData(false); // 排序时保持在当前?": "fetchData(false); // 排序时保持在当前页",
}

def scan_and_fix(directory):
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.vue'):
                filepath = os.path.join(root, file)
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    original_content = content
                    for corrupted, fixed in replacements.items():
                        content = content.replace(corrupted, fixed)
                    
                    if content != original_content:
                        with open(filepath, 'w', encoding='utf-8') as f:
                            f.write(content)
                        print(f"Fixed {filepath}")
                except Exception as e:
                    print(f"Error processing {filepath}: {e}")

if __name__ == "__main__":
    directory = r"d:\Code\internal-site-2\frontend\src\components"
    scan_and_fix(directory)
