
console.log('1. express');
const express = require('express');
console.log('2. prismaClient');
const prisma = require('./prismaClient');
console.log('3. authMiddleware');
const { authMiddleware } = require('./src/middlewares/authMiddleware');
console.log('4. adminMiddleware');
const { adminMiddleware } = require('./src/middlewares/adminMiddleware');
console.log('5. zod');
const { z } = require('zod');
console.log('6. prisma client types');
const { PaymentMethod, InvoiceStatus } = require('@prisma/client');
console.log('7. multer');
const multer = require('multer');
console.log('8. xlsx');
const xlsx = require('xlsx');
console.log('9. fs');
const fs = require('fs');
console.log('10. path');
const path = require('path');
console.log('Testing mkdir...');
const tempUploadDir = path.join(__dirname, '..', 'uploads', 'temp');
console.log('Path:', tempUploadDir);
fs.mkdirSync(tempUploadDir, { recursive: true });
console.log('Done');
