<template>
  <div :class="['transition-all duration-300', isSnapshotMode ? 'fixed inset-0 z-50 bg-slate-50 overflow-auto p-8' : 'space-y-8']">
    
    <!-- Header Section -->
    <div class="flex flex-col gap-6">
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 class="text-2xl font-bold text-slate-900 tracking-tight">销售数据看板</h2>
          <p class="text-slate-500 text-sm mt-1">实时监控关键业务指标与趋势</p>
        </div>
        
        <div class="flex items-center gap-2">
            <!-- Country Selector -->
            <div class="flex items-center bg-white p-1 rounded-xl border border-slate-200 shadow-sm mr-2">
                <button 
                  v-for="country in availableCountries" 
                  :key="country.code"
                  @click="selectedCountry = country.code"
                  :class="[
                    'px-3 py-1.5 text-sm font-medium rounded-lg transition-all',
                    selectedCountry === country.code 
                      ? 'bg-indigo-600 text-white shadow-sm' 
                      : 'text-slate-600 hover:bg-slate-50'
                  ]"
                >
                  {{ country.name }}
                </button>
            </div>

            <div class="flex items-center gap-1 bg-white p-1 rounded-xl border border-slate-200 shadow-sm">
                <button 
                v-for="range in dateRanges" 
                :key="range.value"
                @click="setDateRange(range.value)"
                :class="[
                    'px-3 py-1.5 text-sm font-medium rounded-lg transition-all',
                    currentRange === range.value 
                    ? 'bg-indigo-50 text-indigo-700 shadow-sm ring-1 ring-indigo-200' 
                    : 'text-slate-600 hover:bg-slate-50'
                ]"
                >
                {{ range.label }}
                </button>
            </div>
            
            <!-- Custom Date Inputs -->
            <div v-if="currentRange === 'custom'" class="flex items-center gap-2 bg-white p-1.5 rounded-xl border border-slate-200 shadow-sm animate-fade-in">
                <input type="date" v-model="customStartDate" @change="fetchStats" class="text-sm border-none bg-transparent focus:ring-0 text-slate-600" />
                <span class="text-slate-400">-</span>
                <input type="date" v-model="customEndDate" @change="fetchStats" class="text-sm border-none bg-transparent focus:ring-0 text-slate-600" />
            </div>

            <button 
                @click="toggleSnapshotMode"
                :class="[
                    'ml-2 p-2 rounded-xl transition-all border',
                    isSnapshotMode 
                    ? 'bg-red-50 text-red-600 border-red-200 hover:bg-red-100' 
                    : 'bg-white text-slate-400 border-slate-200 hover:border-indigo-300 hover:text-indigo-600 shadow-sm'
                ]"
                title="快照模式"
            >
                <CameraIcon v-if="!isSnapshotMode" class="w-5 h-5" />
                <XMarkIcon v-else class="w-5 h-5" />
            </button>
        </div>
      </div>
    </div>

    <!-- Snapshot Header (Only visible in Snapshot Mode) -->
    <div v-if="isSnapshotMode" class="mb-8 border-b border-slate-200 pb-4 flex justify-between items-end">
      <div>
        <h1 class="text-3xl font-extrabold text-slate-900 tracking-tight">Overseas Ops Dashboard</h1>
        <p class="text-slate-500 mt-1">Generated by Internal System</p>
      </div>
      <div class="text-right">
        <p class="text-sm font-semibold text-slate-900">Report Date</p>
        <p class="text-2xl font-light text-indigo-600">{{ new Date().toLocaleDateString() }}</p>
      </div>
    </div>

    <!-- Key Metrics Cards -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <!-- GMV Card -->
      <div class="bg-white rounded-2xl p-6 shadow-[0_2px_10px_-3px_rgba(6,81,237,0.1)] border border-slate-100 relative overflow-hidden group">
        <div class="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
          <CurrencyDollarIcon class="w-24 h-24 text-indigo-600 transform rotate-12 translate-x-4 -translate-y-4" />
        </div>
        <div class="flex justify-between items-start relative z-10">
            <div>
                <p class="text-sm font-semibold text-slate-500 uppercase tracking-wider">总销售额 (GMV)</p>
                <div class="mt-2 flex items-baseline gap-2">
                    <span class="text-4xl font-bold text-slate-900">{{ formatCurrency(stats.summary.totalGMV, stats.summary.currency) }}</span>
                    <span class="text-sm font-medium text-slate-400">{{ stats.summary.currency }}</span>
                </div>
                <p v-if="stats.summary.currency !== 'CNY'" class="mt-1 text-sm text-slate-400 font-medium">
                    ≈ {{ formatCurrency(stats.summary.cnyTotalGMV, 'CNY') }}
                </p>
            </div>
            <div :class="['flex items-center px-2.5 py-0.5 rounded-full text-sm font-medium', stats.summary.gmvGrowth >= 0 ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800']">
                <ArrowTrendingUpIcon v-if="stats.summary.gmvGrowth >= 0" class="w-4 h-4 mr-1" />
                <ArrowTrendingDownIcon v-else class="w-4 h-4 mr-1" />
                {{ formatGrowth(stats.summary.gmvGrowth) }}
            </div>
        </div>
      </div>

      <!-- Orders Card -->
      <div class="bg-white rounded-2xl p-6 shadow-[0_2px_10px_-3px_rgba(6,81,237,0.1)] border border-slate-100 relative overflow-hidden group">
        <div class="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
          <ShoppingBagIcon class="w-24 h-24 text-blue-500 transform rotate-12 translate-x-4 -translate-y-4" />
        </div>
        <div class="flex justify-between items-start relative z-10">
            <div>
                <p class="text-sm font-semibold text-slate-500 uppercase tracking-wider">总订单量</p>
                <div class="mt-2 flex items-baseline gap-2">
                    <span class="text-4xl font-bold text-slate-900">{{ stats.summary.totalOrders.toLocaleString() }}</span>
                    <span class="text-sm font-medium text-slate-400">单</span>
                </div>
            </div>
            <div :class="['flex items-center px-2.5 py-0.5 rounded-full text-sm font-medium', stats.summary.ordersGrowth >= 0 ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800']">
                <ArrowTrendingUpIcon v-if="stats.summary.ordersGrowth >= 0" class="w-4 h-4 mr-1" />
                <ArrowTrendingDownIcon v-else class="w-4 h-4 mr-1" />
                {{ formatGrowth(stats.summary.ordersGrowth) }}
            </div>
        </div>
      </div>

      <!-- AOV Card -->
      <div class="bg-white rounded-2xl p-6 shadow-[0_2px_10px_-3px_rgba(6,81,237,0.1)] border border-slate-100 relative overflow-hidden group">
        <div class="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
          <ChartBarIcon class="w-24 h-24 text-emerald-500 transform rotate-12 translate-x-4 -translate-y-4" />
        </div>
        <div class="flex justify-between items-start relative z-10">
            <div>
                <p class="text-sm font-semibold text-slate-500 uppercase tracking-wider">平均客单价(AOV)</p>
                <div class="mt-2 flex items-baseline gap-2">
                    <span class="text-4xl font-bold text-slate-900">{{ formatCurrency(stats.summary.aov, stats.summary.currency) }}</span>
                    <span class="text-sm font-medium text-slate-400">{{ stats.summary.currency }}</span>
                </div>
            </div>
            <div :class="['flex items-center px-2.5 py-0.5 rounded-full text-sm font-medium', stats.summary.aovGrowth >= 0 ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800']">
                <ArrowTrendingUpIcon v-if="stats.summary.aovGrowth >= 0" class="w-4 h-4 mr-1" />
                <ArrowTrendingDownIcon v-else class="w-4 h-4 mr-1" />
                {{ formatGrowth(stats.summary.aovGrowth) }}
            </div>
        </div>
      </div>
    </div>

    <!-- Charts Section -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Trend Chart (Main) -->
      <div class="lg:col-span-2 bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
        <h3 class="text-lg font-bold text-slate-800 mb-6">销售趋势</h3>
        <div class="h-80 w-full">
          <Line v-if="chartData.trend" :data="chartData.trend" :options="chartOptions.trend" />
        </div>
      </div>

      <!-- Platform Distribution -->
      <div class="bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
        <h3 class="text-lg font-bold text-slate-800 mb-6">平台占比</h3>
        <div class="h-64 w-full flex items-center justify-center">
          <Doughnut v-if="chartData.platform" :data="chartData.platform" :options="chartOptions.doughnut" />
        </div>
        <div class="mt-4 space-y-2">
            <div v-for="(item, index) in stats.byPlatform" :key="item.platform" class="flex justify-between text-sm">
                <span class="flex items-center gap-2">
                    <span class="w-3 h-3 rounded-full" :style="{ backgroundColor: chartColors[index % chartColors.length] }"></span>
                    {{ item.platform }}
                </span>
                <span class="font-medium">{{ formatCurrency(item.gmv, stats.summary.currency) }}</span>
            </div>
        </div>
      </div>
    </div>

    <!-- Bottom Row: Country & Top Lists -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
       <!-- Country Performance -->
       <div class="bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
        <h3 class="text-lg font-bold text-slate-800 mb-4">国家表现</h3>
        <div class="space-y-4">
            <div v-for="(item, index) in stats.byCountry" :key="item.code" class="relative">
                <div class="flex justify-between text-sm mb-1">
                    <span class="font-medium text-slate-700">{{ item.name }}</span>
                    <span class="text-slate-900 font-bold">{{ formatCurrency(item.gmv, stats.summary.currency) }}</span>
                </div>
                <div class="w-full bg-slate-100 rounded-full h-2.5">
                    <div class="bg-indigo-600 h-2.5 rounded-full" :style="{ width: getPercentage(item.gmv, stats.summary.totalGMV) + '%' }"></div>
                </div>
            </div>
        </div>
      </div>

      <!-- Top Stores -->
      <div class="bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
        <h3 class="text-lg font-bold text-slate-800 mb-4">Top 5 店铺</h3>
        <ul class="space-y-3">
            <li v-for="(store, index) in stats.topStores" :key="store.name" class="flex items-center justify-between p-3 rounded-lg bg-slate-50">
                <div class="flex items-center gap-3">
                    <span class="flex items-center justify-center w-6 h-6 rounded-full bg-white text-xs font-bold text-slate-500 shadow-sm border border-slate-100">
                        {{ index + 1 }}
                    </span>
                    <span class="text-sm font-medium text-slate-700 truncate max-w-[120px]" :title="store.name">{{ store.name }}</span>
                </div>
                <span class="text-sm font-bold text-indigo-600">{{ formatCurrency(store.gmv, stats.summary.currency) }}</span>
            </li>
        </ul>
      </div>

      <!-- Top Products -->
      <div class="bg-white rounded-2xl p-6 shadow-sm border border-slate-100">
        <h3 class="text-lg font-bold text-slate-800 mb-4">Top 5 热销品(SKU)</h3>
        <ul class="space-y-3">
            <li v-for="(prod, index) in stats.topProducts" :key="prod.sku" class="flex items-center justify-between p-3 rounded-lg bg-slate-50">
                <div class="flex items-center gap-3">
                    <span class="flex items-center justify-center w-6 h-6 rounded-full bg-white text-xs font-bold text-slate-500 shadow-sm border border-slate-100">
                        {{ index + 1 }}
                    </span>
                    <span class="text-sm font-medium text-slate-700 truncate max-w-[120px]" :title="prod.sku">{{ prod.sku }}</span>
                </div>
                <span class="text-sm font-bold text-emerald-600">{{ prod.volume }} 件</span>
            </li>
        </ul>
      </div>
    </div>

  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue';
import { 
  Chart as ChartJS, 
  CategoryScale, 
  LinearScale, 
  PointElement, 
  LineElement, 
  Title, 
  Tooltip, 
  Legend, 
  ArcElement 
} from 'chart.js';
import { Line, Doughnut } from 'vue-chartjs';
import { CameraIcon, XMarkIcon, CurrencyDollarIcon, ShoppingBagIcon, ChartBarIcon, ArrowTrendingUpIcon, ArrowTrendingDownIcon } from '@heroicons/vue/24/outline';
import apiClient from '@/services/apiClient';
import { useAuthStore } from '../../stores/auth';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  ArcElement
);

const authStore = useAuthStore();
const isSnapshotMode = ref(false);
const currentRange = ref('week');
const customStartDate = ref(new Date().toISOString().split('T')[0]);
const customEndDate = ref(new Date().toISOString().split('T')[0]);
const selectedCountry = ref('ALL');

const stats = ref({
    summary: { 
        totalGMV: 0, 
        totalOrders: 0, 
        aov: 0, 
        gmvGrowth: 0, 
        ordersGrowth: 0, 
        aovGrowth: 0, 
        currency: 'CNY', 
        cnyTotalGMV: 0 
    },
    trend: [],
    byPlatform: [],
    byCountry: [],
    topStores: [],
    topProducts: []
});

const dateRanges = [
    { label: '昨日', value: 'yesterday' },
    { label: '本', value: 'week' },
    { label: '本月', value: 'month' },
    { label: '上月', value: 'last_month' },
    { label: '自定义', value: 'custom' }
];

const chartColors = ['#4F46E5', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6'];

// Computed: Available Countries
const availableCountries = computed(() => {
    const list = [];
    if (authStore.role === 'admin') {
        list.push({ code: 'ALL', name: '全部国家' });
        // We could fetch full list, but for now let's use what we have or hardcode common ones if not in store
        // Ideally authStore should have all managed countries if admin, or we fetch from API.
        // Let's assume authStore.supervisedCountries has data or we rely on what's returned by API.
        // For simplicity, let's add common ones or rely on API filter options.
        // Actually, let's just use a static list or what's in authStore if available.
        // Since we don't have a full country list in authStore for admin (it might be empty if they supervise all),
        // let's add the 'ALL' option and maybe let the user pick from a dropdown if we had the list.
        // For now, let's just show 'ALL' and 'ID', 'VN', 'TH', 'MY', 'PH', 'SG' as standard.
        ['ID', 'VN', 'TH', 'MY', 'PH', 'SG'].forEach(c => list.push({ code: c, name: c }));
    } else {
        // For managers, show their operated countries
        (authStore.operatedCountries || []).forEach(c => list.push({ code: c, name: c }));
    }
    return list;
});

// Watch for authStore changes to set default country
watch(() => authStore.operatedCountries, (newVal) => {
    if (authStore.role !== 'admin' && newVal && newVal.length > 0 && selectedCountry.value === 'ALL') {
        selectedCountry.value = newVal[0];
    }
}, { immediate: true });

// Chart Options
const chartOptions = computed(() => {
    const currency = stats.value.summary.currency || 'CNY';
    return {
        trend: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: {
                    mode: 'index',
                    intersect: false,
                    backgroundColor: 'rgba(255, 255, 255, 0.9)',
                    titleColor: '#1e293b',
                    bodyColor: '#475569',
                    borderColor: '#e2e8f0',
                    borderWidth: 1,
                    padding: 10,
                    displayColors: true,
                    callbacks: {
                        label: function(context) {
                            let label = context.dataset.label || '';
                            if (label) {
                                label += ': ';
                            }
                            if (context.parsed.y !== null) {
                                if (context.datasetIndex === 0) { // GMV
                                    label += new Intl.NumberFormat('zh-CN', { style: 'currency', currency: currency }).format(context.parsed.y);
                                } else {
                                    label += context.parsed.y;
                                }
                            }
                            return label;
                        }
                    }
                }
            },
            scales: {
                y: {
                    beginAtZero: true,
                    grid: { borderDash: [2, 4], color: '#f1f5f9' },
                    ticks: { color: '#94a3b8' }
                },
                x: {
                    grid: { display: false },
                    ticks: { color: '#94a3b8' }
                }
            },
            interaction: {
                mode: 'nearest',
                axis: 'x',
                intersect: false
            }
        },
        doughnut: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false }
            },
            cutout: '70%'
        }
    };
});

// Chart Data Computed
const chartData = computed(() => {
    if (!stats.value.trend.length) return {};

    return {
        trend: {
            labels: stats.value.trend.map(t => t.date.slice(5)), // MM-DD
            datasets: [
                {
                    label: '销售额 (GMV)',
                    backgroundColor: 'rgba(79, 70, 229, 0.1)',
                    borderColor: '#4F46E5',
                    pointBackgroundColor: '#4F46E5',
                    pointBorderColor: '#fff',
                    pointHoverBackgroundColor: '#fff',
                    pointHoverBorderColor: '#4F46E5',
                    fill: true,
                    tension: 0.4,
                    data: stats.value.trend.map(t => t.gmv),
                    yAxisID: 'y'
                }
            ]
        },
        platform: {
            labels: stats.value.byPlatform.map(p => p.platform),
            datasets: [{
                backgroundColor: chartColors,
                borderWidth: 0,
                data: stats.value.byPlatform.map(p => p.gmv)
            }]
        }
    };
});

const toggleSnapshotMode = () => {
    isSnapshotMode.value = !isSnapshotMode.value;
};

const setDateRange = (range) => {
    currentRange.value = range;
    if (range !== 'custom') {
        fetchStats();
    }
};

const getPercentage = (val, total) => {
    if (!total) return 0;
    return Math.round((val / total) * 100);
};

const formatCurrency = (val, currency = 'CNY') => {
    return new Intl.NumberFormat('zh-CN', { style: 'currency', currency: currency, maximumFractionDigits: 0 }).format(val);
};

const formatGrowth = (val) => {
    if (val === undefined || val === null) return '0%';
    const sign = val > 0 ? '+' : '';
    return `${sign}${val.toFixed(1)}%`;
};

const fetchStats = async () => {
    // Calculate dates based on range
    let end = new Date();
    let start = new Date();
    
    // Format YYYY-MM-DD helper
    const formatDate = (d) => d.toISOString().split('T')[0];

    if (currentRange.value === 'yesterday') {
        start.setDate(start.getDate() - 1);
        end.setDate(end.getDate() - 1);
    } else if (currentRange.value === 'week') {
        // Start of this week (Monday)
        const day = start.getDay() || 7;
        if (day !== 1) start.setHours(-24 * (day - 1));
    } else if (currentRange.value === 'month') {
        start.setDate(1);
    } else if (currentRange.value === 'last_month') {
        start.setMonth(start.getMonth() - 1);
        start.setDate(1);
        end.setDate(0); // Last day of previous month
    } else if (currentRange.value === 'custom') {
        if (!customStartDate.value || !customEndDate.value) return;
        start = new Date(customStartDate.value);
        end = new Date(customEndDate.value);
    }

    try {
        const res = await apiClient.get('/sales-data/stats', {
            params: {
                startDate: formatDate(start),
                endDate: formatDate(end),
                countryCode: selectedCountry.value
            }
        });
        stats.value = res.data;
    } catch (e) {
        console.error("Failed to fetch stats", e);
    }
};

watch(selectedCountry, () => {
    fetchStats();
});

onMounted(() => {
    fetchStats();
});
</script>
